// Generated by scripts/train-ml-calibration.mjs — do not hand-edit.
export const mlCalibration = {
  "version": 1,
  "generatedAt": "2026-07-01T05:48:18.084Z",
  "method": "Regularized gradient descent (finite-difference, L2 toward prior hand-set constants), chronological train/holdout split. Pure Dixon-Coles Poisson (Soccer) / logistic (MLB) structure unchanged — only coefficients are fitted.",
  "soccer": {
    "source": "/Users/cashmcdearis/Downloads/WorldCupMatches.csv",
    "trainSize": 681,
    "holdoutSize": 171,
    "priors": {
      "formTiltScale": 40,
      "rho": -0.05,
      "baseHomeBoost": 0,
      "drawSoftCap": 0.34
    },
    "fitted": {
      "formTiltScale": 40.05610375967553,
      "rho": -0.04754258687550916,
      "baseHomeBoost": 0.02049184796590607,
      "drawSoftCap": 0.28283421044957974
    },
    "before": {
      "train": {
        "accuracy": 0.4302496328928047,
        "avgBrier": 0.20926782702488325,
        "matches": 681
      },
      "holdout": {
        "accuracy": 0.3567251461988304,
        "avgBrier": 0.21697422690427937,
        "matches": 171
      }
    },
    "after": {
      "train": {
        "accuracy": 0.49926578560939794,
        "avgBrier": 0.20421892523988142,
        "matches": 681
      },
      "holdout": {
        "accuracy": 0.42105263157894735,
        "avgBrier": 0.2095266634396764,
        "matches": 171
      }
    },
    "notFitted": {
      "drawAnchorWeight": "Anchors soccer draw probability toward the live market draw price — no market data exists in the 1930-2014 results file, so this stays hand-set (0.25)."
    }
  },
  "mlb": {
    "source": "/Users/cashmcdearis/Downloads/Data_MLB_2025_StatcastPostseason_PitchByPitch_20251102a.csv",
    "trainSize": 37,
    "holdoutSize": 10,
    "priors": {
      "homeLogit": 0.16,
      "strengthK": 0.27,
      "afterLossScale": 0.6,
      "backtestCompression": 0.78,
      "backtestCap": 0.82
    },
    "fitted": {
      "homeLogit": 0.1601538289544287,
      "strengthK": 0.22694796222421926,
      "afterLossScale": 0.5977146459710325,
      "backtestCompression": 0.7686737703382897,
      "backtestCap": 0.8227007663718198
    },
    "before": {
      "train": {
        "accuracy": 0.40540540540540543,
        "avgBrier": 0.28878637620217584,
        "matches": 37
      },
      "holdout": {
        "accuracy": 0.4,
        "avgBrier": 0.26807324649690584,
        "matches": 10
      }
    },
    "after": {
      "train": {
        "accuracy": 0.3783783783783784,
        "avgBrier": 0.2798790893610451,
        "matches": 37
      },
      "holdout": {
        "accuracy": 0.4,
        "avgBrier": 0.2639021272547209,
        "matches": 10
      }
    },
    "notFitted": {
      "xeraLogitPerRun": "Starter xERA coefficient — the Statcast feed has no live-comparable per-starter season xERA aggregate to fit against, so this stays hand-set (0.35)."
    }
  }
};
